import nodemailer from 'nodemailer';

/**
 * Configure Nodemailer transport
 */
let transporter = null;

export const getTransporter = () => {
  if (transporter) return transporter;

  const senderEmail = process.env.ALERT_SENDER_EMAIL;
  const appPassword = process.env.ALERT_APP_PASSWORD;

  if (!senderEmail || !appPassword) {
    console.warn(
      '[AlertService] ALERT_SENDER_EMAIL or ALERT_APP_PASSWORD is not configured. Email dispatch will be simulated in logs.'
    );
    return null;
  }

  transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: senderEmail,
      pass: appPassword,
    },
  });

  return transporter;
};

/**
 * Send an HTML low-stock alert email to ADMIN_ALERT_EMAIL
 * @param {Object} item - Mongoose Item document or object
 * @returns {Promise<boolean>}
 */
export const dispatchLowStockAlert = async (item) => {
  const adminEmail = process.env.ADMIN_ALERT_EMAIL;
  const senderEmail = process.env.ALERT_SENDER_EMAIL || 'inventory-alerts@stoqra.local';

  const recommendedRestock = Math.max((item.reorderLevel * 2) - item.currentStock, 10);
  const isOutOfStock = item.currentStock <= 0;
  const severityBadge = isOutOfStock
    ? '<span style="background-color: #dc2626; color: #ffffff; padding: 4px 10px; border-radius: 9999px; font-size: 12px; font-weight: bold;">OUT OF STOCK</span>'
    : '<span style="background-color: #f59e0b; color: #ffffff; padding: 4px 10px; border-radius: 9999px; font-size: 12px; font-weight: bold;">LOW STOCK WARNING</span>';

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f3f4f6; margin: 0; padding: 24px; }
          .card { background-color: #ffffff; border-radius: 8px; padding: 28px; max-width: 600px; margin: 0 auto; box-shadow: 0 4px 6px rgba(0,0,0,0.05); border: 1px solid #e5e7eb; }
          .header { border-bottom: 1px solid #e5e7eb; padding-bottom: 16px; margin-bottom: 20px; }
          .title { font-size: 20px; color: #111827; margin: 0 0 8px 0; font-weight: 700; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #f3f4f6; font-size: 14px; }
          th { color: #6b7280; font-weight: 600; background-color: #f9fafb; }
          td { color: #1f2937; }
          .highlight { font-weight: bold; color: #dc2626; }
          .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
        </style>
      </head>
      <body>
        <div class="card">
          <div class="header">
            <div style="margin-bottom: 10px;">${severityBadge}</div>
            <h1 class="title">Inventory Alert: Action Required for ${item.name}</h1>
            <p style="color: #4b5563; margin: 0; font-size: 14px;">The inventory level for SKU <strong>${item.sku}</strong> has reached or dropped below its reorder threshold.</p>
          </div>

          <table>
            <tr>
              <th>SKU</th>
              <td><strong>${item.sku}</strong></td>
            </tr>
            <tr>
              <th>Product Name</th>
              <td>${item.name}</td>
            </tr>
            <tr>
              <th>Current Stock</th>
              <td class="highlight">${item.currentStock} units</td>
            </tr>
            <tr>
              <th>Reorder Threshold</th>
              <td>${item.reorderLevel} units</td>
            </tr>
            <tr>
              <th>Current Unit Cost</th>
              <td>₹${Number(item.unitCost || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td>
            </tr>
            <tr>
              <th>Suggested Restock Qty</th>
              <td style="color: #2563eb; font-weight: bold;">+${recommendedRestock} units</td>
            </tr>
          </table>

          <div style="background-color: #eff6ff; border-left: 4px solid #3b82f6; padding: 12px 16px; border-radius: 4px; font-size: 13px; color: #1e40af;">
            <strong>Recommendation:</strong> Place a purchase order with your supplier for at least ${recommendedRestock} units to maintain service levels.
          </div>

          <div class="footer">
            <p>Automated notification generated by Stoqra Inventory Management System at ${new Date().toISOString()}</p>
          </div>
        </div>
      </body>
    </html>
  `;

  try {
    const transport = getTransporter();

    if (!transport || !adminEmail) {
      console.log(
        `[AlertService - Simulated] Low stock alert for SKU "${item.sku}" (${item.name}). Current: ${item.currentStock}, Reorder: ${item.reorderLevel}. Recommended restock: +${recommendedRestock}`
      );
      return false;
    }

    const info = await transport.sendMail({
      from: `"Stoqra Inventory Alerts" <${senderEmail}>`,
      to: adminEmail,
      subject: `🚨 [INVENTORY ALERT] ${item.sku} (${item.name}) is Low on Stock (${item.currentStock}/${item.reorderLevel})`,
      html: htmlContent,
    });

    console.log(`[AlertService] Alert email sent successfully for SKU ${item.sku}. MessageId: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error(`[AlertService] Failed to send email alert for SKU ${item.sku}:`, error.message);
    return false;
  }
};

export default { dispatchLowStockAlert, getTransporter };
